### ISSUE TITLE
mundle install

### ISSUE THREAD

**Issue by meelash** [meelash/Mundlejs#15]
Packages, like npm, cpan etc.

mundle install jquery@1.5.333

Should be relatively easy to implement, but very, very cool.

Real client-side package management.

**Comment by meelash** [comment]
This is coming now. Full steam ahead! Not sure how long it will take...

**Comment by meelash** [comment]
Wrote all the tests for the client-side requests according to the new api.

**Comment by meelash** [comment]
Client-side tests passing, working on server-side

**Comment by tauren** [comment]
Are you leveraging Twitter Bower for client-side packages like Yeoman does? Or is this yet another client-side package manager? 

http://yeoman.io/
https://github.com/twitter/bower

**Comment by meelash** [comment]
Hi tauren, I am in fact using Bower. It's a very nice, clean library, pleasure to work with. I actually started out with the (bad) idea of forking it and adding some features... but realized later that was a useless time-sink. Simple is better. Unfortunately, life interrupted, so although it will be quite easy to do this now, I need to find a few hours to work on it. Hopefully soon, maybe this week.

**Comment by meelash** [comment]
Server-side tests are passing for the new request format from the client.

Still need to write tests for the new request format in dependencies and test for loading a mundle without main defined in the package.json.

Then need to add the cli wrapper around bower to make the usage seamless.

**Comment by meelash** [comment]
Tests are passing for path resolution of nested dependencies in mundles. Still need test for loading a mundle without main defined in the package.json.

Then need to add the cli wrapper around bower to make the usage seamless.

**Comment by meelash** [comment]
Completed writing and passing all tests. Last bit is the cli wrapper.

**Comment by meelash** [comment]
Done! Finally! Can't believe it took 6 months before I could get back to it, time flies.
